export const RULES = {
  'generator-star-spacing': 'error',
  'style/array-bracket-newline': ["error", "consistent"],
  'style/array-bracket-spacing': ["error", "never"],
  'style/array-element-newline': ["error", "consistent"],
  'style/arrow-parens': ['error', 'as-needed'],
  'style/arrow-spacing': 'error',
  'style/block-spacing': 'error',
  'style/brace-style': 'error',
  'style/comma-dangle': ['error', 'always-multiline'],
  'style/comma-spacing': 'error',
  'style/comma-style': 'error',
  'style/computed-property-spacing': 'error',
  'style/dot-location': ['error', 'property'],
  'style/function-call-argument-newline': ['error', 'consistent'],
  'style/function-call-spacing': 'error',
  'style/function-paren-newline': 'error',
  'style/generator-star-spacing': ['error', { after: true, before: false }],
  'style/implicit-arrow-linebreak': 'error',
  'style/indent': ['error', 2],
  'style/key-spacing': 'error',
  'style/keyword-spacing': 'error',
  'style/lines-between-class-members': 'error',
  'style/member-delimiter-style': 'error',
  'style/newline-per-chained-call': 'error',
  'style/no-confusing-arrow': 'error',
  'style/no-extra-semi': 'error',
  'style/padding-line-between-statements': [
    'error',
    { blankLine: 'always', next: 'return', prev: '*' },
    { blankLine: 'always', next: '*', prev: ['const', 'let', 'var'] },
    { blankLine: 'always', next: ['const', 'let', 'var'], prev: '*' },
    { blankLine: 'any', next: ['const', 'let', 'var'], prev: ['const', 'let', 'var'] },
    { blankLine: 'always', next: '*', prev: 'if' },
    { blankLine: 'always', next: 'if', prev: '*' },
  ],
  'style/yield-star-spacing': ['error', { after: true, before: false }],
}

